name: 'nais SLSA Provenance Action'
description: 'Action to generate signed SLSA provenance'
branding:
  icon: lock
  color: red
inputs:

  repo_dir:
    description: |-
      Internal value (do not set): root of directory to search for build files.
      Defaults to "github.workspace".
    required: false
    default: ${{ github.workspace }}

  repo_sub_dir:
    description: |-
      Specify a subdirectory if build file not found in working root directory.
    required: false
    default: ""

  repo_name:
    description: |-
      Name of the generated provenance. Used as an relative path under "github.workspace".
      Defaults to "github.repository".
    required: false
    default: ${{ github.repository }}

  key:
    description: |-
      The key used to sign the attestation.
    required: true

  docker_user:
    description: |-
      Docker login user. 
      Defaults to "github.actor".
    required: false
    default: ""

  docker_pwd:
    description: |-
      Docker login password.
    required: true

  dependencies:
    description: |-
      If salsa should generate materials for the provenance containing dependencies.
      Defaults to true.
    required: false
    default: "true"

  image:
    description: |-
      The docker container to sign.
    required: false
    default: ""

  maven_opts:
    description: |-
      Space seperated string with additional maven cli options.
    required: false
    default: ""

  github_context:
    description: |-
      Internal value (do not set): the "github" context object in json.
      The context is used when generating provenance.
    required: false
    default: ${{ toJSON(github) }}

  runner_context:
    description: |-
      Internal value (do not set): the "runner" context object in json.
      The context is used when generating provenance.
    required: false
    default: ${{ toJSON(runner) }}

runs:
  using: 'docker'
  image: 'docker://ghcr.io/nais/salsa:v0.1'
  args:
    - ${{ inputs.repo_dir }}
    - ${{ inputs.repo_name }}
    - ${{ inputs.github_context }}
    - ${{ inputs.runner_context }}
    - ${{ inputs.image }}
    - ${{ inputs.env_context }}
    - ${{ inputs.repo_sub_dir }}
    - ${{ inputs.key }}
    - ${{ inputs.docker_user }}
    - ${{ inputs.docker_pwd }}
    - ${{ inputs.dependencies }}
