name: 'NAIS SLSA Provenance Action'
description: 'A POC Action to generate signed SLSA provenance'
branding:
  icon: lock
  color: red
inputs:

  repo_dir:
    description: |-
      Path to other than root directory.
    required: false

  repo_name:
    description: |-
      Name of the file and path to provenance.
      Used as an relative path under $GITHUB_WORKSPACE 
      to place the genrated files.
      Defaults to "github.repository".
    required: true
    default: ${{ github.repository }}

  generate_artifacts:
    description: |-
      Can be set to true, for upload-artifact action or other use.
    required: false
    default: 'false'

  gcp_credentials:
    description: |-
      Gcp serviceuser account key in json. This is required credentials and are used for 
      
       We recommend using a service account with the least permissions necessary.
      
      signing and verifying the generated slsa provenance.
    required: true

  github_context:
    description: |-
      Internal value (do not set): the "github" context object in json.
      The context is used when generating provenance.
    required: true
    default: ${{ toJSON(github) }}

  runner_context:
    description: |-
      Internal value (do not set): the "runner" context object in json.
      The context is used when generating provenance.
    required: true
    default: ${{ toJSON(runner) }}

  env_context:
     description: |-
      Internal value (do not set): the "env" context object in json.
     required: false
     default: ${{ env }}

outputs:
  artifacts:
    description: |-
      The path to provenance artifacts generated relative to $GITHUB_WORKSPACE.
    value: ${{ steps.served-salsa.outputs.artifacts }}

runs:
  using: 'composite'
  steps:

    # Prepare image
    - name: Prepare current repository image and repo name
      id: cosign-ttl
      shell: bash
      run: |
        repo="${REPO_NAME##*/}"
        image=ttl.sh/"${repo}":1h
        echo "::set-output name=image::${image}"
        echo "::set-output name=repo_name::${repo}"
      env:
        REPO_NAME: ${{ inputs.repo_name }}

    # Needed for attest to sign and verify command
    - name: Build and push current provenance container to sign
      id: ttl
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.cosign-ttl.outputs.image }}

    # checkout salsa / could be done with binary
    - name: Misanplace Salsa
      uses: actions/checkout@v2
      with:
        repository: nais/salsa
        path: './prepped-salsa'

    # env to file google credentials
    - name: Google auth and credentials
      id: google
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ inputs.gcp_credentials }}
        create_credentials_file: true

    # Prepare environment variables for docker run
    - name: docker container environment
      id: docker-envs
      shell: bash
      run: |
        salsa_docker_image=nais/salsa:latest
        encoded_github="$(echo ${GITHUB_CONTEXT} | base64 -w 0)"
        encoded_runner="$(echo ${RUNNER_CONTEXT} | base64 -w 0)"
        encoded_env="$(echo ${ENV_CONTEXT} | base64 -w 0)"
        gcp_path="${GCP_CREDENTIAL_PATH##*/}"
        echo "::set-output name=github::${encoded_github}"
        echo "::set-output name=runner::${encoded_runner}"
        echo "::set-output name=env_s::${encoded_env}"
        echo "::set-output name=gcp_creds::${gcp_path}"
        echo "::set-output name=salsa_image_with_tag::${salsa_docker_image}"
      env:
        GITHUB_CONTEXT: ${{ inputs.github_context }}
        RUNNER_CONTEXT: ${{ inputs.runner_context }}
        ENV_CONTEXT: ${{ inputs.env_context }}
        GCP_CREDENTIAL_PATH: ${{ steps.google.outputs.credentials_file_path }}

    - name: Build Salsa
      id: docker-salsa
      uses: docker/build-push-action@v2
      with:
        push: false
        load: true
        tags: ${{ steps.docker-envs.outputs.salsa_image_with_tag }}
        file: './prepped-salsa/Dockerfile'
        context: .
        build-args: |
          dir=${{ github.workspace }}
          repo=${{ steps.cosign-ttl.outputs.repo_name }}
          image=${{ steps.cosign-ttl.outputs.image }}
          github=${{ steps.docker-envs.outputs.github  }}
          runner=${{ steps.docker-envs.outputs.runner }}
          env_s=${{ steps.docker-envs.outputs.env_s }}
          gcp_cred_path=${{ steps.docker-envs.outputs.gcp_creds }}

    # Pico-de-gallo
    - name: Make Salsa - Pico-de-Gallo
      run: |
        docker run ${{ steps.docker-envs.outputs.salsa_image_with_tag }}
      shell: bash
        #env:
      # SALSA_SCAN_REPO_DIR: ${{ github.workspace }}
      #SALSA_SCAN_REPO: ${{ steps.cosign-ttl.outputs.repo_name }}
      #SALSA_SCAN_GITHUB_CONTEXT: ${{ steps.docker-envs.outputs.github }}
      #SALSA_SCAN_RUNNER_CONTEXT: ${{ steps.docker-envs.outputs.runner }}
      #SALSA_REPO_IMAGE: ${{ steps.cosign-ttl.outputs.image }}
      #GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.docker-envs.outputs.gcp_creds }}

    # Serving salsa lovers
    - name: Serving salsa lovers
      if: ${{ inputs.generate_artifacts == 'true' }}
      id: served-salsa
      run: |
        output=extracted-artifacts-$(date +'%Y-%m-%d')
        docker cp "$(docker create $SALSA_IMAGE)":/salsa/artifacts/ ./${output}
        echo "::set-output name=artifacts::${output}"
      shell: bash
      env:
        SALSA_IMAGE: ${{ steps.docker-envs.outputs.salsa_image_with_tag }}