name: 'NAIS SLSA Provenance Action'
description: 'A POC Action to generate signed SLSA provenance'
branding:
  icon: lock
  color: red
inputs:
  repo_dir:
    description: |-
      path to directory of artifacts
    required: false
  repo_name:
    description: |-
      path to write build provenance file
    required: true
  image:
    description: |-
      docker image to pull and sign
    required: true
  gcp_credentials:
    description: |-
      gcp serviceuser credentials to sign and upload the slsa provenance
    required: true
  github_context:
    description: |-
      internal (do not set): the "github" context object in json
    required: true
    default: ${{ toJSON(github) }}
  runner_context:
    description: |-
      internal (do not set): the "runner" context object in json
    required: true
    default: ${{ toJSON(runner) }}
  # env_context:
  #   description: 'internal (do not set): the "env" context object in json'
  #   required: false
  #   default: ${{ toJSON(env) }}
runs:
  using: 'composite'
  steps:

    # Prepare image
    - name: Image Name
      id: cosign-ttl
      shell: bash
      run: |
        image=ttl.sh/${IMAGE_NAME}:1h
        echo "::set-output name=image::${image}"
      env:
        IMAGE_NAME: ${{ inputs.repo_name }}

    # Needed for attest command, prepare here
    - name: Build and push
      id: ttl
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.cosign-ttl.outputs.image }}

    # checkout salsa
    - uses: actions/checkout@v2
      with:
        repository: nais/salsa
        path: salsa

    # auth to and google credentials
    - name: Google auth
      id: google
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ inputs.gcp_credentials }}
        export_default_credentials: true
        credentials_file_path: /gha-credentials.json

    # Prepare args for docker run
    - name: docker arguments
      id: docker-args
      shell: bash
      run: |
        encoded_github="$(echo ${GITHUB_CONTEXT} | base64 -w 0)"
        encoded_runner="$(echo ${RUNNER_CONTEXT} | base64 -w 0)"
        gcp_path="${GCP_CREDENTIAL_PATH##*/}"
        echo "::set-output name=github::${encoded_github}"
        echo "::set-output name=runner::${encoded_runner}"
        echo "::set-output name=gcp_creds::${gcp_path}"
      env:
        GITHUB_CONTEXT: ${{ inputs.github_context }}
        RUNNER_CONTEXT: ${{ inputs.runner_context }}
        GCP_CREDENTIAL_PATH: ${{ steps.google.outputs.credentials_file_path }}

    # Build container we need to perform commands
    # Can be done more smooth with download of binary from repo
    # and installation files
    - name: Build Salsa
      id: salsa
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: nais/salsa:latest
        context: .
        build-args: |
          repo=${{ inputs.repo_name }}
          image=${{ steps.cosign-ttl.outputs.image }}
          github=${{ steps.docker-args.outputs.github }}
          runner=${{ steps.docker-args.outputs.runner }}
          gcp_cred_path=${{ steps.docker-args.outputs.gcp_creds }}

    # Pico-de-gallo
    - name: Make Salsa
      run: |
        docker run nais/salsa:latest
      shell: bash