name: slsa keyless
on:
  workflow_run:
    workflows: [Salsa build & release]
    types: [completed]
    branches: [main]
env:
  IMAGE: ttl.sh/nais/salsa-keyless-test:1h
jobs:
  on-failure:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed' && exit 1
  keyless:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # ratchet:actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # ratchet:google-github-actions/auth@v1.0.0
        id: google
        with:
          workload_identity_provider: ${{ secrets.SLSA_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: cosign-keyless@plattformsikkerhet-dev-496e.iam.gserviceaccount.com
          token_format: "id_token"
          id_token_audience: sigstore
          id_token_include_email: true
      - name: Build and push
        id: docker
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # ratchet:docker/build-push-action@v4
        with:
          context: integration-test
          push: true
          tags: ${{ env.IMAGE }}
      - name: Generate provenance, sign and upload image
        uses: ./
        with:
          image_digest: ${{ steps.docker.outputs.digest }}
          registry: ttl.sh
          identity_token: ${{ steps.google.outputs.id_token }}
        env:
          COSIGN_EXPERIMENTAL: "true"
