name: slsa keyless
on:
  workflow_run:
    workflows: [Salsa build & release]
    types: [completed]
    branches: [main]
env:
  IMAGE: ttl.sh/nais/salsa-keyless-test:1h
jobs:
  on-failure:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed' && exit 1
  keyless:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # ratchet:actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # ratchet:google-github-actions/auth@v0.8.1
        id: google
        with:
          workload_identity_provider: ${{ secrets.SLSA_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: cosign-keyless@plattformsikkerhet-dev-496e.iam.gserviceaccount.com
          token_format: "id_token"
          id_token_audience: sigstore
          id_token_include_email: true
      - name: Build and push
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # ratchet:docker/build-push-action@v3
        with:
          context: integration-test
          push: true
          tags: ${{ env.IMAGE }}
      - name: Generate provenance, sign and upload image
        uses: ./
        with:
          identity_token: ${{ steps.google.outputs.id_token }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          COSIGN_EXPERIMENTAL: "true"