name: NAIS SALSA

on: push

jobs:
  generate-provenance:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate provenance
        uses: ./
        with:
          # for org or for each repo?
          gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          path: ./artifacts/